[package]
name = "detection_app"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33"
rfd = "0.16"
opencv = { version = "0.97", default-features = false, features = ["videoio", "imgproc", "highgui"]}
image = "0.25"
